server:
  port: 8189
  servlet:
    context-path: /app

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
#    ?currentShema=hider

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
